# Generated by Django 5.1 on 2024-09-30 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_cartitem'),
        ('restaurants', '0007_alter_menuitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='productName',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurants.menuitem'),
            preserve_default=False,
        ),
    ]
