# Generated by Django 5.1 on 2024-10-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_cartitem_productname_cartitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='totalPrice',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='productName',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
